// No Copyright. Vladislav Aleinik 2019
#ifndef COMPUTING_GRID_HPP_INCLUDED
#define COMPUTING_GRID_HPP_INCLUDED

enum RequestType
{
	I_WANT_TASKS,
	HERE_IS_YOUR_TASK,
	TASK_DONE
};



#endif  // COMPUTING_GRID_HPP_INCLUDED

